databases:
  - name: teacherplatform-db
    plan: free
    databaseName: TutorBD 
    ipAllowList: []      

services:
  - type: web
    name: teacherplatform
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production  
      - key: ConnectionStrings__TutorDbContext
        value: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
      - key: ASPNETCORE_DATA_PROTECTION__KEYS__PATH
        value: /app/keys
    disk:
      name: data_keys      
      mountPath: /app/keys
      sizeGB: 1