databases:
  - name: teacherplatform-db
    plan: free
    databaseName: TutorBD
    ipAllowList: []

services:
  - type: web
    name: teacherplatform
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__TutorDbContext
        value: "Server=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD};"
      - key: ASPNETCORE_DATA_PROTECTION__KEYS__PATH
        value: /app/keys
    disk:
      name: data_keys
      mountPath: /app/keys
      sizeGB: 1